### ISSUE TITLE
Default value is not applied unless preference is written to DB?

### ISSUE THREAD

**Issue by f1nnix** [agateblue/django-dynamic-preferences#189]
Hi, thank for for building ddp.

Here's my setting:

```python
@user_preferences_registry.register
class NotificationLevel(ChoicePreference):
    section = 'general'
    name = 'notification_level'
    choices = [
        ('none', 'None'),
        ('related', 'Related'),
        ('all', 'All'),
    ]
    default = 'related'
```

I need to query all users, who have 'notification_level' == 'related'. I've got 10 users total. For 3 of them I set setting to 'all'. 

```python
for user in (user1, user2, user3):
    user.preferences['genertal__notification_level'] = 'all'
```

I query users with 'related' value:

```python
UserPreferenceModel.objects.filter(
    section='general',
    raw_value='related',
    name='notification_level'
)
```

And get `[]`. It's obvious: though 'related' is default setting, it's written to DB and associated with user only **AFTER** setting for particular user is accessed.

How to get users, who have or **should** have 'related' value? The only workaround is to query users, who:

* have no target setting at all
* have target setting with value 'ralted'

and merge two sets. Is it true?

If yes, could you please give an example of request to User model, which will return all users, who have no specific setting?

**Comment by EliotBerriot** [comment]
This should work:

```python
not_matching_preferences = UserPreferenceModel.objects.filter(
    section='general',
    name='notification_level'
).exclude(raw_value='related')
users = User.objects.exclude(pk__in=not_matching_preferences.values('id')
```

If I'm not mistaken, this will give you all users, excluding those who have the preference set to anything other than `related`. This should include users with no preferences, or users with the preference set to the default value. Let me know if it works :)

You can also use this alternative to simplify your query:

1. Add a signal handler when a user is created, and in the handler, simply access all the user preferences (via `user.preferences.all()`). This will ensure all preferences are persisted in DB for the user
2. (optionally if you have existing data): add a migration or run a script to do the same thing for existing users
3. Query as shown in your post with `UserPreferenceModel.objects.filter(section='general', raw_value='related', name='notification_level')` (this will work because all users will have their settings set)

For fields you'll use in SQL queries though, I'd probably recommend adding the field to the user model directly if it's an option. It's going to make your life easier, and yield simpler and more performant SQL queries.
