### ISSUE TITLE
Multi-value "list of choices" preference type

### ISSUE THREAD

**Issue by czlee** [agateblue/django-dynamic-preferences#40]
Our use-case is as follows:
- We would like the user to be able to specify a list of things in a single preference.
- Each "thing" is one of a set of predefined choices (like in `ChoicePreference`).
- On a preference form, the user should be presented with a series of (ordered) dropdown boxes.
- The allowed choices for all elements in the list are the same.
- Choices may be selected multiple times in the list, or not at all. So it's not, for example, "please rank these from 1 to 5".
- It'd be nice if the length of the list were variable, but that'd be hard, so we just ran a fixed-length list, with the ability to leave some blank.

In our specific case, users are specifying how teams in a competition should be ranked. They can choose from a predefined list of metrics ("number of wins", "total score", "number of judges that voted for you"). Teams are then ranked first by the first metric, then by the second metric, and so on.

Here's an implementation:
https://github.com/czlee/tabbycat/blob/43ce83615f8f5bf3dd6d4ba8b7f45ba54f0c53d1/options/forms.py
https://github.com/czlee/tabbycat/blob/43ce83615f8f5bf3dd6d4ba8b7f45ba54f0c53d1/options/serializers.py
https://github.com/czlee/tabbycat/blob/43ce83615f8f5bf3dd6d4ba8b7f45ba54f0c53d1/options/types.py

Here's how it works:
-  The preference type is `MultiValueChoicePreference`, and takes the following attributes that subclasses specify: `choices`, `nfields` and `allow_empty`.
- There is a serializer `MultiValueSerializer` that just converts a list to a delimited string, and back again. The delimiter I've used is "//", but that's easily changed. (The delimiter can't be in choice values, otherwise it'll break.)
- It uses subclasses of Django's  [`MultiValueField`](https://docs.djangoproject.com/en/1.9/ref/forms/fields/#multivaluefield) and [`MultiWidget`](https://docs.djangoproject.com/en/1.9/ref/forms/widgets/#multiwidget) to implement having several choice fields.
- If `allow_empty` is set to true, then the field will purge the list of empty choices as part of its `compress()` implementation. As a consequence, if a user saves the preference with non-consecutive elements non-empty, the non-empty values will be pushed up so that they are consecutive from the first element. For example, if you save ['A', 'B', None, 'C', None, 'D'], it'll be saved as ['A', 'B', 'C', 'D']. Information about middle empty elements is lost. (This is appropriate for our use-case, at least.)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1725499/13000632/41918326-d111-11e5-89d0-f93882e13359.png)

Hopefully that made sense—it's a little hard to explain fully in text, so sorry if it didn't and feel free to ask more.

Is this use case sufficiently general that you'd be interested in having it added to this project? I'm happy to contribute it to this project, but thought it might be too niche, so thought I'd ask to see what you think.

**Comment by EliotBerriot** [comment]
Wow, that's an amazing piece of work ! I think your implementation is very clean, considering the complexity of your use case, and I'm glad you're offering to share it :)

The use case globally makes sense, however, I find it a bit specific to be implemented "as is" in the package. The way I see it, we should rather implement a generic `MultiValuePreference`, using the serializer you wrote and some parts of your logic. This preference type would store ordered, arbitrary values.

Then, we would customize the behaviour of this preference by providing custom fields / attributes:

```python
class FavoriteNumbers(MultiValuePreference):
    """A preference that require the user to choose 4 integers"""
    max_length = 4
    value_field_class = forms.IntegerField() 
    value_serializer = IntegerSerializer
    
class FavoriteBlogEntries(MultiValuePreference):
    """A preference that offer the user to choose up to ten blog entries"""
    max_length = 10
    value_field_class = forms.ModelChoiceField(queryset=BlogEntry.objects.all())
    value_serializer = ModelSerializer
    allow_empty = True
    
class FavoriteFruits(MultiValuePreference):
    """A preference that offers 6 choices to the user, 
    allows empty values and removes empty values before serialization"""
    max_length = 6
    choices = [
        ('apple', 'Apple'),
        ('banana', 'Banana'),
        ('strawberry', 'Strawberry'),
        # other fruits here
    ]
    value_field_class = forms.ChoiceField(choices=choices) 
    allow_empty = True

    # if True, empty values are inserted in database, right now there stripped away 
    store_empty = False 

    # Will raise validation error if the same value is selected multiple times
    allow_duplicates = False 

class TeamStandingsPrecedence(MultiValuePreference):
    """And finally, your use case (assuming I understood everything properly)"""
    choices = get_metric_choices()
    max_length = 8
    allow_empty = True
    store_empty = False
    allow_duplicates = True
    value_field_class = forms.ChoiceField(choices=choices) 
    default = ['points', 'speaks_avg']
```

This way, we could reuse a lot of your logic for other use cases. It seems doable to me, but would it fit your needs ?

**Comment by czlee** [comment]
Thank you! This makes sense. I think it would fit our needs as you describe. I thought about implementing a more generic `MultiValuePreference` as an intermediate, but got lazy/thought it was too hard, probably mainly because I hadn't considered specifying the field in the MultiValuePreference class. I think we'd have to run `value_field_class` and `value_field_kwargs` separately so that they can be instantiated repeatedly, but I could see this working.

I suppose the `value_field_*` attributes would then be mandatory? Like, the means of specifying whether values are integers or strings *etc.* is through `value_field_class` and `value_serializer` only?

**Comment by EliotBerriot** [comment]
If it seems okay to you, we probably can start to work on it.

> I think we'd have to run value_field_class and value_field_kwargs separately so that they can be instantiated repeatedly, but I could see this working.

Yes, this should probably work as you described.

> I suppose the value_field_* attributes would then be mandatory? Like, the means of specifying whether values are integers or strings etc. is through value_field_class and value_serializer only?

Yes, they would be mandatory. The problem here is that we have two serialization/deserialization steps : 

1. We have to serialize each value of the list
2. Then we serialize the whole list 

Since we will write a base class for this preference type, step 1 would be implicit (any `MultiValuePreference` will, in the end, serialize a list). However, step two must be explicit. Maybe there is some way to deduce serializer automatically based on the form field used (IntegerField -> IntegerSerializer, etc.), but this is the kind of thing I'd rather implement later.

I totally forgot @ka7eh was also working on a implementation of  a`MultiValuePreference`. He submitted a pull request implementing this feature today (#43). I think is work and yours can be used as a base for a generic multivalue preference.  I especially like the use of Python CSV writer to serialize the value list, since it should prevent issues that may arise with delimiters present in values.

@Ka7eh, I apologize to you, because I hadn't a clear vision of how the `MultiValuePreference` should behave when you started to work on this feature. Since the code you wrote adress a specific use case (multiple choices), pretty much like the one @czlee shared in this issue, we'll have to make it more generic before merging it in the package.

Hopefully, thanks to Ka7eh pull request, czlee code and the more precise vision we have on the ideal API for this use case, we should be able to implement a pretty generic and usable preference type.
